- hosts: lab
  gather_facts: no
  vars:
    random_string: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits,punctuation') }}"
  vars_files:
    vars/emp.yml
  tasks:
    - debug: var=hostvars[inventory_hostname].ansible_port
    - set_fact: ansible_port=2222
    # name: Add apt-HTTPS
    # become: yes
    # apt:
    #   pkg: ['apt-transport-https']
    #   install_recommends: no
    - include: tasks/add-srv.yml
    # debug: var=add_repos
    # debug: var=add_repokeys
    - debug: var=emp_install

# handlers:
#   - include: handlers/site.yml
