- hosts: lab
  gather_facts: no

  tasks:
    - debug: var=hostvars[inventory_hostname].ip6

    - include: tasks/ssh-port.yml

    - name: /etc/network/interfaces with IPv6 address
      template: src=template/interfaces.j2 dest=/etc/network/interfaces
      become: yes
      register: nic

    - name: Restart eth0 (ETA 3.25 seconds)
      become: yes
      shell: "/sbin/ifdown --exclude=lo -a; sleep 1; /sbin/ifup --exclude=lo -a"
      register: res
      when: nic is changed
    - debug: var=res
      when: nic is changed

    - name: Replace systemd (stage 1 - install sysvinit-core etc.)
      become: yes
      apt:
        update_cache: no
        pkg: ['sysvinit-core','sysvinit-utils']
        install_recommends: no
      register: initsystem

    - name: Reboot to replace systemd (ETA 23 seconds) if sysvinit just installed
      become: yes
      reboot: # Ansible 2.7 required
      register: res
      when: initsystem is changed
    - debug: var=res
      when: initsystem is changed

    - name: Replace systemd (stage 2 - uninstall systemd)
      become: yes
      apt:
        state: absent
        purge: yes
        autoremove: yes
        pkg: ['systemd']
      register: res
    - debug: var=res

  handlers:
    - include: handlers/site.yml
