- hosts: lab
  gather_facts: no
  vars:
    random_string: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits,punctuation') }}"
    old_keys:
      - "/etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg"
      - "/etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg"
    repo_list:
      - "deb http://packages.dotdeb.org     jessie all  # nginx"
      - "deb https://packages.sury.org/php/ jessie main # php5.6"
      - "deb [arch=amd64] http://lon1.mirrors.digitalocean.com/mariadb/repo/10.1/debian jessie main"
    repo_keys:
      - 7E3F070089DF5277 # www.dotdeb.org/dotdeb.gpg
      - AC0E47584A7A714D # packages.sury.org/php/apt.gpg
      - CBCB082A1BB943DB # package-signing-key@mariadb.org

  tasks:
    - debug: var=hostvars[inventory_hostname].ansible_port
    - set_fact: ansible_port=2222
    - name: Add apt-HTTPS
      become: yes
      apt:
        pkg: ['apt-transport-https']
        install_recommends: no
    - include: tasks/add-srv.yml
    - debug: var=add_repos
    - debug: var=add_repokeys

# handlers:
#   - include: handlers/site.yml
