- hosts: lab
  gather_facts: no
  vars:
    random_string: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits,punctuation') }}"

  tasks:
    - debug: var=hostvars[inventory_hostname].ansible_port
    - set_fact: ansible_port=2222
    - include: tasks/reclaim-swrsvd.yml

# handlers:
#   - include: handlers/site.yml
