- hosts: provisioner
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Gather facts about user account
      digital_ocean_account_facts:
        oauth_token: "{{ do_api_token }}"
      register:  do_acct

    - debug: var=do_acct
