- hosts: provisioner
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
  # - digital_ocean_sshkey_facts:
  #     oauth_token: "{{ do_api_token }}"

  # - set_fact:
  #     pubkey: "{{ item.public_key }}"
  #   with_items: "{{ ssh_keys|json_query(ssh_pubkey) }}"
  #   vars:
  #     ssh_pubkey: "[?name=='ansible_ctrl']"

  # - debug:
  #     msg: "{{ pubkey }}"

    - name: Ensure DO has SSH key '{{ do_ssh_name }}' registered
      digital_ocean:
        state: present
        command: ssh
        name: "{{ do_ssh_name }}"
        ssh_pub_key: "{{ do_ssh_pub_key }}"
        api_token: "{{ do_api_token }}"
      register: presentkey

    - debug: var=presentkey
      changed_when: False
