- hosts: provisioner
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Ensure DO has SSH key '{{ do_ssh_name }}' registered
      digital_ocean:
        state: present
        command: ssh
        name: "{{ do_ssh_name }}"
        ssh_pub_key: "{{ do_ssh_pub_key }}"
        api_token: "{{ do_api_token }}"
      register: presentkey

    - debug: var=presentkey
      changed_when: no
