- hosts: provisioner
  gather_facts: no
  vars:
    arubau: "{{ lookup('ini', 'user   section='+acct+'  '+secrets) }}"
    arubap: "{{ lookup('ini', 'passwd section='+acct+'  '+secrets) }}"
    secrets: file=~/.ssh/aruba/ansible.ini
    acct: acct0
    wait_minutes: 20
  tasks:
    - name: Ensure server is like new - reinit (re-image) from current template - ETA 3-{{wait_minutes}} minutes
      it_aruba_smart_vm:
        state: pristine
        user: "{{ arubau }}"
        password: "{{ arubap }}"
        dc: 1
        name: La
        wait: true
        wait_time: "{{wait_minutes * 60}}"
        timeout: 12
      register:  r1

    - name: Print result
      debug: var=r1

    - name: Add VM to in-memory (dynamic) inventory
      add_host:
        name: lab
        groups: dohosts
        ansible_host: "{{ r1.srv.ip4 }}"
        ansible_user: root
        ansible_ssh_pass: "{{ r1.srv.password0 }}"
        set_port: 22390
        ip6: "{{ r1.srv.ip6 }}"
        ansible_ssh_extra_args: '-o StrictHostKeyChecking=accept-new' # need OpenSSH >= 7.6
      changed_when: false

    - name: Delete existing SSH host key
      shell: "ssh-keygen -R {{ r1.srv.ip4 }}"
      changed_when: false

- hosts: dohosts #TODO ensure StrictHostKeyChecking=yes
  gather_facts: no
  vars:
    do_ssh_pub_key:  "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    random_string: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits,punctuation') }}"

  vars_files:
    - defaults/main.yml
    - vars.yml

  tasks:
    - include: tasks/ssh-rootkey.yml
    - include: tasks/nic-reset.yml
    - include: tasks/sysvinit.yml
    - include: tasks/ssh-port.yml

    - include: tasks/swap.yml
    - include: tasks/software.yml
    - include: tasks/security.yml
    - include: tasks/users.yml

  handlers:
    - include: handlers/site.yml
