- hosts: provisioner
  gather_facts: no
  vars_files:
    - do1.yml
  tasks:
    - name: Gather facts about SSH key (fingerprint look-up)
      shell: "echo {{ root_ssh_pk }} | awk '{print $2}' | base64 -d | md5sum -b | sed 's/../&:/g; s/: .*$//'"
      register: cmd_res
      changed_when: no
    - set_fact: kfprint="{{ cmd_res.stdout }}"

    - digital_ocean_sshkey_facts:
        oauth_token: "{{ do_api_token }}"
      register: do_keys

    - set_fact:
        pubkeyid: "{{ item.id }}"
        pubkeyn:  "{{ item.name }}"
      with_items: "{{ ssh_keys|json_query(pk) }}"
      vars:
        pk: "[?fingerprint=='{{ kfprint }}']"

  # - debug: msg="SSH key {{ kfprint }} found, id={{ pubkeyid }}, name={{ pubkeyn }}"

    - name: Find or create Droplet, then register in-memory
      digital_ocean_droplet: # FIXME auto-add host key on the 1st connection
        state: present
        name: "{{ do_name }}"
        region_id: "{{ do_region }}"
        size_id: "{{ do_size }}"
        image_id: "{{ do_image }}"
        ssh_keys: "{{ pubkeyid }}"
        unique_name: yes
        ipv6: "{{ needIPv6 }}"
        private_networking: no
        oauth_token: "{{ do_api_token }}"
        wait_timeout: 240 # wait for DO response, default is 120 (2 minutes), usually it's under 2 minutes.
      register: vm

    - debug: msg="Droplet {{do_name}} {{vm.data.ip_address}} {{vm.data.ipv6_address | default('-')}}"

    - name: Add droplet to in-memory (dynamic) inventory
      add_host:
        name: do1
        groups: dohosts
        ansible_host: "{{ vm.data.ip_address }}"
        ansible_user: root
        ansible_ssh_extra_args: '-o StrictHostKeyChecking=accept-new' # need OpenSSH >= 7.6
      changed_when: false

- hosts: dohosts #TODO ensure StrictHostKeyChecking=yes
  gather_facts: no
  vars_files:
    - defaults/main.yml
    - do1.yml
  vars:
    set_port: "{{ ssh_port }}"

  tasks:
    - include: tasks/ssh-port.yml
    - include: tasks/swap.yml
    - include: tasks/software.yml
    - include: tasks/security.yml
    - include: tasks/users.yml

  handlers:
    - include: handlers/site.yml
