- hosts: provisioner
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Gather facts about SSH key (fingerprint look-up)
      shell: "echo {{ do_ssh_pub_key }} | awk '{print $2}' | base64 -d | md5sum -b | sed 's/../&:/g; s/: .*$//'"
      register: cmd_res
      changed_when: no
    - set_fact: kfprint="{{ cmd_res.stdout }}"

    - digital_ocean_sshkey_facts:
        oauth_token: "{{ do_api_token }}"
      register: do_keys

    - set_fact:
        pubkeyid: "{{ item.id }}"
        pubkeyn:  "{{ item.name }}"
      with_items: "{{ ssh_keys|json_query(ssh_pubkey) }}"
      vars:
        ssh_pubkey: "[?fingerprint=='{{ kfprint }}']"

  # - debug: msg="SSH key {{ kfprint }} found, id={{ pubkeyid }}, name={{ pubkeyn }}"

    - name: Find or create Droplet, then register in-memory
      digital_ocean_droplet: # FIXME auto-add host key on the 1st connection
        state: present
        name: "{{ do_name }}"
        region_id: "{{ do_region }}"
        size_id: "{{ do_size }}"
        image_id: "{{ do_image }}"
        ssh_keys: "{{ pubkeyid }}"
        unique_name: yes
        ipv6: no
        private_networking: no
        oauth_token: "{{ do_api_token }}"
        wait_timeout: 240 # wait for DO response, default is 120 (2 minutes), usually it's under 2 minutes.
      register: do_droplet

  # - debug: msg="Droplet {{ do_name }} {{ do_droplet.data.ip_address }}"

    - name: Add droplet to in-memory (dynamic) inventory
      add_host:
        name: do1
        groups: dohosts
        ansible_ssh_host: "{{ do_droplet.data.ip_address }}"
        ansible_ssh_user: root
      changed_when: false

- hosts: dohosts #TODO ensure StrictHostKeyChecking=yes
  gather_facts: no
  vars:
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

  vars_files:
    - defaults/main.yml
    - vars.yml

  tasks:
    - name: Wait for SSH connection to a new droplet (some 4-5 seconds is OK) # KILLME
      wait_for_connection: timeout=30 # default: 600 seconds
    - include: tasks/swap.yml
    - include: tasks/software.yml
    - include: tasks/security.yml
    - include: tasks/users.yml

  handlers:
    - include: handlers/site.yml
