- hosts: provisioner
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Gather facts about SSH key '{{ do_ssh_pub_key }}' (check fingerprint)
      shell: "echo {{ do_ssh_pub_key }} | awk '{print $2}' | base64 -d | md5sum -b | sed 's/../&:/g; s/: .*$//'"
      register: cmd_res
      changed_when: no
    - set_fact: kfprint="{{ cmd_res.stdout }}"
  # - debug: var=kfprint

    - digital_ocean_sshkey_facts:
        oauth_token: "{{ do_api_token }}"
      register: do_keys

    - set_fact:
        pubkeyid: "{{ item.id }}"
        pubkeyn:  "{{ item.name }}"
      with_items: "{{ ssh_keys|json_query(ssh_pubkey) }}"
      vars:
        ssh_pubkey: "[?fingerprint=='{{ kfprint }}']"

    - debug: msg="SSH key {{ kfprint }} found, id={{ pubkeyid }}, name={{ pubkeyn }}"

    - name: Find or create Droplet, then register in-memory
      digital_okean:
        command: droplet
        state: present
        name: "{{ do_name }}"
        region_id: "{{ do_region }}"
        size_id: "{{ do_size }}"
        image_id: "{{ do_image }}"
        ssh_key_ids: "{{ pubkeyid }}"
        unique_name: yes
        ipv6: no
        private_networking: no
        api_token: "{{ do_api_token }}"
       #wait_timeout: 240 # default is 300 (5 minutes), usually it's under 2 minutes.
      register: do_droplet

  # - debug: msg="Droplet {{ do_name }} {{ do_droplet.droplet.ip_address }}"

    - name: Add droplet to in-memory (dynamic) inventory
      add_host:
        name: do1
        groups: dohosts
      # ansible_python_interpreter: /usr/bin/python3 # DO Ubuntu 18.04 image has no 'python' or 'python2'
        ansible_ssh_host: "{{ do_droplet.droplet.ip_address }}"
        ansible_ssh_user: root
      # ansible_ssh_extra_args: '-o StrictHostKeyChecking=no' # TODO auto-add host key on 1st connection
      changed_when: false

    - name: Wait for SSH connection
      wait_for_connection:
        delay: 2
       #timeout: 120 # default 600 seconds

- hosts: dohosts
  gather_facts: no  #TODO ensure StrictHostKeyChecking=yes
  vars:
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

  vars_files:
    - defaults/main.yml
    - vars.yml

  tasks:
    - include: tasks/swap.yml
    - include: tasks/software.yml
    - include: tasks/security.yml
    - include: tasks/users.yml

  handlers:
    - include: handlers/site.yml
