- name: Ensure server is like new. ETA 3-{{ wait_minutes }} minutes
  it_aruba_smart_vm:
    state: pristine
    user: "{{ aruba_account }}"
    password: "{{ aruba_password }}"
    dc: "{{ vm.dc }}"
    name: "{{ vm.name }}"
    wait: true
    wait_time: "{{ wait_minutes * 60 }}"
    timeout: 12
  delegate_to: localhost
  register: t0

- name: Fill 'vm' details (on rebuild)
  loop:
    - {'k':'vm', 'v':"{{ vm|combine({'ip4':t0.srv.ip4, 'ip6':t0.srv.ip6|default(omit), 'server':t0.srv}, recursive=True) }}"}
    - {'k':'ansible_host', 'v':'{{ t0.srv.ip4 }}'}
    - {'k':'ansible_user', 'v':'root'}
    - {'k':'todo_port', 'v':'{{ ansible_port }}'}  # save inventory target
    - {'k':'ansible_port', 'v': 22}
  set_fact:
    "{{ item['k'] }}": "{{ item['v'] }}"

- name: Delete old SSH host keys if any
  known_hosts:
    state: absent
    host: "{{ item }}"
  delegate_to: localhost
  when: t0 is success
  loop: [ "{{ t0.srv.ip4 }}", "{{ ansible_host }}" ]

- name: Add ssh pubkey to ~root/.ssh/authorized_keys
  authorized_key: user=root state=present key={{ root_pubkey }}
  vars:
    ansible_ssh_pass: "{{ t0.srv.password0 }}"
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=accept-new' # need OpenSSH >= 7.6

- name: If defined IPv6 address, fix /etc/network/interfaces
  template: src=interfaces.j2 dest=/etc/network/interfaces
  when: t0.srv.ip6 is defined
  vars:
    ip6: "{{ t0.srv.ip6 }}"
