- block:

  - name: If state==pristine ensure server is like new. ETA 3-{{wait_minutes}} minutes.
    it_aruba_smart_vm:
      state: pristine
      user: "{{ aruba_account }}"
      password: "{{ aruba_password }}"
      dc: "{{ dc }}"
      name: "{{ vm_name }}"
      wait: true
      wait_time: "{{ wait_minutes * 60 }}"
      timeout: 12
    delegate_to: localhost
    register: vm0

  - name: Delete old SSH host keys if any
    known_hosts:
      state: absent
      host: "{{ item }}"
    delegate_to: localhost
    when: vm0 is success
    loop: [ "{{ vm0.srv.ip4 }}", "{{ ansible_host }}" ]

  - name: Add ssh pubkey to ~root/.ssh/authorized_keys
    authorized_key: user=root state=present key={{ root_pubkey }}
    #delegate_to: "{{vm0.srv.ip4}}"
    vars:
      ansible_port: 22
      ansible_ssh_pass: "{{ vm0.srv.password0 }}"
      ansible_user: root
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=accept-new' # need OpenSSH >= 7.6

  - name: fix /etc/network/interfaces - set IPv6 address (if defined)
    template: src=interfaces.j2 dest=/etc/network/interfaces
    #delegate_to: "{{vm0.srv.ip4}}"
    when: vm0.srv.ip6 is defined
    vars:
      ansible_user: root
      ip6: "{{vm0.srv.ip6}}"

  when: state == 'pristine'


- block:

  - name: If state==present find or create server, ensure it's ON. ETA 3-{{wait_minutes}} minutes.
    it_aruba_smart_vm:
      state: present
      user: "{{ aruba_account }}"
      password: "{{ aruba_password }}"
      dc: "{{ dc }}"
      name: "{{ vm_name }}"
      wait: true
      wait_time: "{{ wait_minutes * 60 }}"
      timeout: 12
    delegate_to: localhost
    register: um0

  when: state == 'present'

- name: Set 'um' fact (on rebuild)
  set_fact:
    um:
      ip4: "{{ vm0.srv.ip4 }}"
      ip6: "{{ vm0.srv.ip6 | default(none) }}"
      server: "{{ vm0.srv }}"
  when: vm0 is success and vm0 is not skipped

- name: Set 'um' fact (no rebuild)
  set_fact:
    um:
      ip4: "{{ um0.srv.ip4 }}"
      ip6: "{{ um0.srv.ip6 | default(none) }}"
      server: "{{ um0.srv }}"
  when: um0 is success and um0 is not skipped

- name: Disable root password
  user: name=root password='!'
  #delegate_to: "{{um.ip4}}"
  vars:
    ansible_user: root
    ansible_ssh_extra_args: '-o PasswordAuthentication=no'

- name: check presence of /dev/vg/lv_swap
  shell: "if [ -b /dev/vg/lv_swap ]; then echo vg-lv_swap; fi"
  #delegate_to: "{{um.ip4}}"
  register: res
  changed_when: no
  vars:
    ansible_user: root

- name: Flag swap LV found (skip otherwise).
  set_fact: swap_lv=yes
  when: res.stdout == "vg-lv_swap"

- name: Flag swap LV not found (skip otherwise).
  set_fact: swap_lv=no
  when: res.stdout != "vg-lv_swap"

- block:

  - name: Turn-off swap
    shell: "if [ -b /dev/vg/lv_swap ]; then /sbin/swapoff /dev/mapper/vg-lv_swap; fi"
    #delegate_to: "{{um.ip4}}"
    vars:
      ansible_user: root

  - name: Delete swap from /etc/fstab
    lineinfile: dest=/etc/fstab line="/dev/mapper/vg-lv_swap none            swap    sw              0       0" state=absent
    #delegate_to: "{{um.ip4}}"
    vars:
      ansible_user: root

  - name: Delete LV
    shell: "/sbin/lvremove -f /dev/vg/lv_swap"
    #delegate_to: "{{um.ip4}}"
    vars:
      ansible_user: root

  - name: Extend LV lv_root
    shell: "/sbin/lvextend -l +100%FREE /dev/vg/lv_root"
    #delegate_to: "{{um.ip4}}"
    vars:
      ansible_user: root

  - name: Extend lv_root's / filesystem
    shell: "/sbin/resize2fs /dev/vg/lv_root"
    #delegate_to: "{{um.ip4}}"
    vars:
      ansible_user: root

  when: swap_lv|bool
