- name: If state==pristine ...
  include_tasks: aruba-anew.yml
  when: state == 'pristine'

- name: If state==present ...
  include_tasks: aruba-present.yml
  when: state == 'present'

- name: Disable root password
  user: name=root password='!'
  vars:
    ansible_ssh_extra_args: '-o PasswordAuthentication=no'

- name: Check /dev/vg/lv_swap presence
  shell: "if [ -b /dev/vg/lv_swap ]; then echo vg-lv_swap; fi"
  register: t0
  changed_when: no

- name: If lv_swap found, stop using it for swap and reclaim its space
  include_tasks: reclaim-swrsvd.yml
  when: t0.stdout == "vg-lv_swap"
