- name: Ensure server is like new. ETA 2-{{wait_minutes}} minutes.
  digital_ocean_droplet:
    rebuild: yes
    name: "{{ vm.name }}"
    image: "{{ vm.image | default(none) }}"
    oauth_token: "{{ do_api_token }}"
    wait_timeout: "{{ wait_minutes * 60 }}"
  delegate_to: localhost
  register: t1

- name: Delete old SSH host keys if any
  known_hosts:
    state: absent
    host: "{{ item }}"
  delegate_to: localhost
  when: t1 is success
  loop: [ "{{ t1.data.ip_address }}", "{{ vm.name }}" ]
