- name: Find or create Droplet
  digital_ocean_droplet:
     state: present
     unique_name: yes
     name: "{{ vps_name }}"
     region_id: "{{ dc }}"
     size_id: "{{ size }}"
     image:  "{{ image }}"
     ssh_keys: "{{ pubkeyid }}"
     ipv6: "{{ needIPv6 }}"
     private_networking: "{{ private_net }}"
     oauth_token: "{{ do_api_token }}"
     wait_timeout: "{{ wait_minutes * 60 }}" # wait for DO response, default is 120
  register: vm
