- name: Delete swap from /etc/fstab
  lineinfile: dest=/etc/fstab line="/dev/mapper/vg-lv_swap none            swap    sw              0       0" state=absent

- name: Turn off swap, delete lv_swap, extend lv_root && resize2fs
  shell: >
    if [ -b /dev/vg/lv_swap ]; then /sbin/swapoff /dev/mapper/vg-lv_swap; fi;
    /sbin/lvremove -f /dev/vg/lv_swap &&
    /sbin/lvextend -l +100%FREE /dev/vg/lv_root &&
    /sbin/resize2fs /dev/vg/lv_root
