- name: Install updates
  apt: upgrade=dist update_cache=yes

- name: Install essential packages
  apt:
    pkg: ['ntp']

- name: Ensure services is running and enabled
  service: name="{{ item }}" state=started enabled=yes
  with_items:
    - ntp
