# https://dmsimard.com/2016/03/15/changing-the-ssh-port-with-ansible/
- name: Set SSH Port {{ todo_port }}, no UseDNS, AcceptEnv
  lineinfile: >
    path=/etc/ssh/sshd_config
    regexp='^#?{{ item.key }}'
    line='{{ item.key }} {{ item.value }}'
    validate='/usr/sbin/sshd -t -f %s'
  register: s0
  with_items:
    - {key: 'Port', value: '{{ todo_port }}'}
    - {key: 'UseDNS', value: 'no'}
    - {key: 'AcceptEnv', value: ''}

- name: Restart sshd
  service: name=ssh state=restarted
  when: s0 is changed
  changed_when: false

- name: Use port {{ todo_port }} from now
  set_fact: ansible_port={{ todo_port }}
