- hosts: provisioner
  gather_facts: no
  vars:
    arubau: "{{ lookup('ini', 'user   section='+acct+'  '+secrets) }}"
    arubap: "{{ lookup('ini', 'passwd section='+acct+'  '+secrets) }}"
    secrets: file=~/.ssh/aruba/ansible.ini
    acct: acct0
    wait_minutes: 20

  tasks:
    - name: Get servers DC1
      it_aruba_smart:
        user: "{{ arubau }}"
        password: "{{ arubap }}"
        dc: 1
      register: r1
    - name: Show servers in DC1
      debug: msg="Busy:{{ item.busy }} ID:{{ item.id }} IP {{ item.ip4 }} name:{{ item.name }}"
      loop: "{{ r1.srv }}"
